name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: asg-linux-amd64
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: asg.exe
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: asg-darwin-amd64
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: asg-darwin-arm64
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true

      - name: Move binary and assets to build directory
        run: cp -r ./assets ./build && cp ./target/${{ matrix.platform.target }}/release/asg ./build
        if: matrix.platform.os_name != 'Windows-x86_64'

      - name: Move binary and assets to build directory
        run: cp -r ./assets ./build && cp ./target/${{ matrix.platform.target }}/release/asg.exe ./build
        if: matrix.platform.os_name == 'Windows-x86_64'

      - name: Remove .gitkeep
        run: rm -f ./build/.gitkeep

      - name: Archive build directory
        run: tar cvfz asg-${{ inputs.tag || github.ref_name }}-linux-amd64.tar.gz build/*

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workdir: build
          # ref_name is the tag.
          title: "ASG-${{ inputs.tag || github.ref_name }}"
          tag: "${{ inputs.tag || github.ref_name }}"
        # This can fail if the release already exists. Let's ignore that.
        continue-on-error: true

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "*.tar.gz"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: "${{ inputs.tag || github.ref_name }}"
